# This is a basic workflow to help you get started with Actions

name: Hugo on Github Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ src ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Runs a single command using the runners shell
    - name: Clean directory ./public/
      run: |
        rm -rf .git/worktrees/public/ 
        rm -fr ./public/

    # Runs a set of commands using the runners shell
    - name: Publish to ./public/
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.73.0'
      run: |
        git worktree add -B master public origin/master
        hugo -b https://jessun2017.github.io
